'use strict';
const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const { render, parseRules, extractFix, MAX_BYTES } = require('../scripts/sync-plugin-guidance');

const repoRoot = path.join(__dirname, '..', '..');
const master = fs.readFileSync(path.join(repoRoot, 'claude-security-guidance.md'), 'utf8').replace(/\r\n/g, '\n');

test('digest render is deterministic', () => {
  assert.equal(render(), render());
});

test('digest is under the 8192-byte Anthropic cap', () => {
  assert.ok(Buffer.byteLength(render(), 'utf8') <= MAX_BYTES, 'plugin-guidance.md exceeds the 8 KB cap');
});

test('digest carries one cue for every rule in the master', () => {
  const out = render();
  const rules = parseRules(master);
  assert.ok(rules.length >= 37, 'expected the master to parse to >=37 rules');
  for (const r of rules) {
    assert.ok(out.includes(`**${r.id}** · ${r.title}`), `${r.id} missing from the digest`);
  }
  // exactly one cue line per rule (no dupes, no drops)
  const cueCount = out.split('\n').filter((l) => /^- \*\*SOL-\d{3}\*\* · /.test(l)).length;
  assert.equal(cueCount, rules.length, 'digest cue count != rule count');
});

test('every rule body yields a non-empty single-line fix cue', () => {
  for (const r of parseRules(master)) {
    const fix = extractFix(r.body);
    assert.ok(fix.length > 0, `${r.id}: empty fix cue`);
    assert.ok(!fix.includes('\n') && !fix.includes('|'), `${r.id}: fix cue has a newline/pipe`);
    assert.ok(!/\*\([^)]*\)\*$/.test(fix), `${r.id}: trailing *(provenance)* leaked into the cue`);
  }
});

test('extractFix strips the trailing *(...)* note before finding "Fix:" (anti-corruption)', () => {
  // a future rule whose provenance note itself contains "Fix:" must not corrupt the cue
  assert.equal(extractFix('Bug here. Fix: `require_keys_neq!`. *(superseded the old Fix: hack)*'), '`require_keys_neq!`');
  assert.equal(extractFix('Bug. Fix: do the right thing. *(2 wins)*'), 'do the right thing');
  assert.throws(() => extractFix('A body with no remedy clause at all.'), /no "Fix:" clause/);
});

test('digest keeps the threat model + checklist + a full-detail pointer', () => {
  const out = render();
  assert.match(out, /## Threat model/);
  assert.match(out, /## Review checklist/);
  assert.match(out, /list_solana_security_rules/); // points at the MCP tool for full detail
  assert.match(out, /claude-security-guidance\.md/); // and at the full master
  assert.match(out, /GENERATED by/); // self-declares generated
});

test('committed plugin-guidance.md is in sync with the generator', () => {
  const committed = fs.readFileSync(path.join(repoRoot, 'plugin-guidance.md'), 'utf8').replace(/\r\n/g, '\n');
  assert.equal(committed, render(), 'plugin-guidance.md is stale — run npm run sync:plugin-guidance');
});
